//顶部状态栏
import { BarGlobal,OperateEnum } from "../../model/system/System_global.slint";
import { FFButton } from "../../widgets/FFButton.slint";
import { FFTheme,Theme } from "../../Theme.slint";
import { Button } from "std-widgets.slint";

component Bar inherits Rectangle{
    
    property <bool> drag-area-pressed: false;
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;
    in property <string> title;
    in property <image> logo;
    in-out property <bool> is-move: false;
    in-out property <MouseCursor> barCursor: MouseCursor.default;
    in-out property <Theme> theme: FFTheme.theme;

    

    area := TouchArea{
        moved => {
            if(is-move){
                BarGlobal.move((self.mouse-x - drag-area-down-x) / 1px,(self.mouse-y - drag-area-down-y) / 1px);
            }
        }
        pointer-event(ev) => {
            drag-area-pressed = ev.kind == PointerEventKind.down;
            drag-area-down-x = self.mouse-x;
            drag-area-down-y = self.mouse-y;
            //如果右键点击，弹出菜单
            if(ev.button == PointerEventButton.right && ev.kind == PointerEventKind.up){
                pwin.show();
            }else if(ev.button == PointerEventButton.left && ev.kind == PointerEventKind.down){
                is-move = true;
                barCursor = MouseCursor.move;
            }else if(ev.button == PointerEventButton.left && ev.kind == PointerEventKind.up){
                is-move = false;
                barCursor = MouseCursor.default;
            }
        }
        mouse-cursor: barCursor;
    }

    pwin := PopupWindow {
        width: 100px;
        height: 80px;
        x: area.mouse-x;
        y:area.mouse-y;
        Rectangle {
            width: 100px;
            height: 80px;
            border-width: 1px;
            border-color: #F2F2F2;
            VerticalLayout {
                FFButton {
                    button-name: "亮主题";
                    clicked => {
                        FFTheme.theme = FFTheme.bright;
                    }
                }
                FFButton {
                    button-name: "暗主题";
                    clicked => {
                        FFTheme.theme = FFTheme.dark;
                    }
                }
            }
            
        }
    }

    Rectangle {
        height: 40px;
        background: theme.bar-background-color;
        border-radius: 4px;
        drop-shadow-color: theme.bar-shadow-color;
        drop-shadow-offset-x: 0px;
        drop-shadow-offset-y: 3px;
        drop-shadow-blur: 5px;

        HorizontalLayout {
            alignment: LayoutAlignment.space-between;
            Rectangle {
                width: 120px;
                height: 40px;
                HorizontalLayout {
                    alignment: LayoutAlignment.start;
                    Rectangle {
                        width: 40px;
                        height: 40px;
                        Image {
                            width: 30px;
                            height: 30px;
                            source: logo;
                        }
                    }
                    
                }
                
            }
            Rectangle {
                width: 120px;
                height: 40px;
                Text {
                    height: 40px;
                    text: title;
                    font-size: 15px;
                    color: theme.bar-text-color;
                    vertical-alignment: TextVerticalAlignment.center;
                }
            }
            Rectangle {
                width: 120px;
                HorizontalLayout {
                    alignment: LayoutAlignment.end;
                    FFButton { 
                        ff-width: 40px;
                        ff-height: 40px;
                        ff-drop-shadow-blur: 0px;
                        ff-drop-shadow-offset-x: 0px;
                        ff-drop-shadow-offset-y: 0px;
                        ff-border-radius: 0px;
                        theme: FFTheme.theme.grey-button;
                        button-name: "—";
                        clicked => {
                            BarGlobal.window-operate(OperateEnum.minimize);
                        }
                    }
                    FFButton { 
                        ff-width: 40px;
                        ff-height: 40px;
                        ff-drop-shadow-blur: 0px;
                        ff-drop-shadow-offset-x: 0px;
                        ff-drop-shadow-offset-y: 0px;
                        ff-border-radius: 0px;
                        theme: FFTheme.theme.grey-button;
                        button-name: "口";
                        clicked => {
                            BarGlobal.window-operate(OperateEnum.maximize);
                        }
                    }
                    FFButton { 
                        ff-width: 40px;
                        ff-height: 40px;
                        ff-drop-shadow-blur: 0px;
                        ff-drop-shadow-offset-x: 0px;
                        ff-drop-shadow-offset-y: 0px;
                        ff-border-radius: 0px;
                        theme: FFTheme.theme.grey-button;
                        button-name: "X";
                        clicked => {
                            BarGlobal.window-operate(OperateEnum.close);
                        }
                    }
                }
                
            }
        }

    }

}


export { Bar }


