import { Bar } from "components/system/Bar.slint";
import { BarGlobal,OperateEnum } from "./model/system/System_global.slint";
import { Win } from "components/system/Win.slint";
import { FFButton } from "widgets/FFButton.slint";
import { FFTheme } from "Theme.slint";

export { BarGlobal,OperateEnum}

component Main inherits Window {
    
    property <image> logo: @image-url("./assets/logo/logo.png");

    icon: logo;
    //最小尺寸目前不支持，只有第一次启动起作用
    min-width: 800px;
    min-height: 600px;
    background: transparent;
    no-frame: true;

    Win {
        win-width: self.width;
        win-height: self.height;
        background: transparent;
        VerticalLayout {
            alignment: LayoutAlignment.start;
            //标题栏
            Bar { 
                background: transparent;
                title: "软件模版";
                logo: @image-url("./assets/logo/logo.svg");
            }
            //内容
            Rectangle {
                background: transparent;
                VerticalLayout {
                    alignment: LayoutAlignment.start;
                    
                }
            }
        }
    }

}

export { Main }


