import { Bar } from "components/system/Bar.slint";
import { BarGlobal,OperateEnum } from "./model/system/System_global.slint";
import { Win } from "components/system/Win.slint";

export { BarGlobal,OperateEnum}

component Main inherits Window {
    
    property <image> logo: @image-url("./assets/icon/icon.png");

    icon: logo;
    min-width: 700px;
    min-height: 500px;
    no-frame: true;

    Win {
        win-width: self.width;
        win-height: self.height;
        VerticalLayout {
            alignment: LayoutAlignment.start;
            Bar { 
                title: "软件模版";
                logo: logo;
            }
        }
    }

}

export { Main }


